Write-Host "[SPR-002] Smoke manual (paso a paso)"
Write-Host ""
Write-Host "1) Backend:"
Write-Host "   cd backend"
Write-Host "   ./mvnw test"
Write-Host "   ./mvnw spring-boot:run"
Write-Host ""
Write-Host "2) Healthcheck en otra terminal:"
Write-Host "   curl http://localhost:8080/actuator/health"
Write-Host "   curl http://localhost:8080/api/ping"
Write-Host ""
Write-Host "3) Frontend:"
Write-Host "   cd frontend"
Write-Host "   npm install"
Write-Host "   npm run dev"
Write-Host ""
Write-Host "4) Verifica en consola que Vite muestre el estado 'ready'."